name: Deploy to Render

on:
  push:
    branches:
      - default

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Replace Secrets in application.properties
        run: |
          sed -i 's/REPLACE_ME_TWILIO_ACCOUNT_SID/${{ secrets.twilio_account_sid }}/g' src/main/resources/application.properties
          sed -i 's/REPLACE_ME_TWILIO_AUTH_TOKEN/${{ secrets.twilio_auth_token }}/g' src/main/resources/application.properties
        env:
          twilio_account_sid: ${{ secrets.twilio_account_sid }}
          twilio_auth_token: ${{ secrets.twilio_auth_token }}
